### ISSUE TITLE
How to use token for restriction

### ISSUE THREAD

**Issue by long1012** [futurestudio/hapi-rate-limitor#128]
hi，guys，my  have a problem，The same token can only access the interface 10 times a minute。In other words, how to change the method of getting ID to get token, and the request header also has token

**Comment by marcuspoehls** [comment]
@long1012 Hey Allen, you could use a custom `getIp` function or define a property on the authenticated credentials (`request.auth.credentials` aka user).

### Custom `getIp` function
Here’s an example how you may use a function determining the token identifying an incoming request. Please notice that the function name `getIp` is not restricted to return an IP address. You can return any kind of identifier that rate limits the given request:

```
await server.register({
  plugin: require('hapi-rate-limitor'),
  options: {
    getIp: async (request) => {
      return request.headers['x-your-token-header-name']
    }
  }
})
```


### Dynamic rate limits
If the token is also part of the authenticated credentials, you may use [dynamic rate limits](https://github.com/futurestudio/hapi-rate-limitor#dynamic-rate-limits) via the `userAttribute`. For example, you may set the `userAttribute` option to `'token'` if your `request.auth.credentials` look this:

```js
// request.auth.credentials may look like the object below
{
  id: 1,
  name: 'Marcus',
  token: 'abc123'
}
```

**Comment by long1012** [comment]
Hi, This is the code I wrote, but it doesn't work. Did I write something wrong
await server.register({
      plugin: require('hapi-rate-limitor'),
      options: { 
        userAttribute: 'id',
        userLimitAttribute: 'rateLimit',
        max: 10,
        duration: 60 * 1000,
        getIp: async (request) => {
          request.auth.credentials = {
            id: 1,
            rateLimit: 10,
            name: request.headers['authToken']
          }
          return request.headers['authToken']
        },
      }
    })

**Comment by marcuspoehls** [comment]
@long1012 Is one of the ways working for you?

**Comment by marcuspoehls** [comment]
Closing this issue. Please reopen of you need further help :)
