### ISSUE TITLE
How does RedIS connect to the cluster

### ISSUE THREAD

**Issue by ZZXM** [futurestudio/hapi-rate-limitor#133]
How does RedIS connect to the cluster

**Comment by marcuspoehls** [comment]
@ZZXM Hey, this package uses [ioredis](https://github.com/luin/ioredis) for Redis connections. Use the `redis` option to configure your Redis connection. The `hapi-rate-limitor` plugin just passes the connections through to ioredis.

**Notice** this rate limiting package doesn’t use a Redis cluster connection. It connects via `new IoRedis(options)`.

Here’s an example how you configure Redis options:

```js
await server.register({
  plugin: require('hapi-rate-limitor'),
  options: {
    redis: {
      db: 0
      port: 6379,
      host: '127.0.0.1',
      password: 'super-secret',
    },
  }
})
```

You can also use a Redis connection string (URL):


```js
await server.register({
  plugin: require('hapi-rate-limitor'),
  options: {
    redis: "redis://:password@127.0.0.1:6379/1"
  }
})
```

**Comment by marcuspoehls** [comment]
I’m closing this here. Feel free to re-open this issue if my answer is missing something :)
