### ISSUE TITLE
skip attribute not working.

### ISSUE THREAD

**Issue by varun17398** [futurestudio/hapi-rate-limitor#191]
Seems like skip attribute is not working as expected. I did exactly the way document suggested even then that particular request is not being skipped by rate limiter. Please check the code and screenshots.
`'use strict';

const Hapi = require('@hapi/hapi');
const { request } = require('express');

const init = async () => {

    const server = Hapi.server({
        port: 3000,
        host: 'localhost'
    });

    await server.register({
        plugin: require('hapi-rate-limitor'),
        max: 10,
        duration: 60*1000,
        enabled: true,
        userAttribute: async (request) => {
            return request.info.remoteAddress
        },
        userLimitAttribute: 'rateLimit',
        skip: async (request) => {
            // if(request.headers['api_key']) return false
            // else return true
            return request.path.includes('/admin')
        }
    })

    server.route({
        method: 'GET',
        path: '/admin',
        options:{
            plugins: {
                'hapi-rate-limitor': {
                    max: 10,              // a maximum of 10 requests
                    duration: 60 * 1000 // for 2 minutes
                }
            }
        },
        handler: (request, h) => {
            console.log(request.headers['api_key']);
            console.log(request.path.includes('/admin'));
            if(request.headers['api_key']){
                console.log("true 1");
            }
            else{
                console.log("false 1")
            }

            return 'Hello World! admin';
        }
    });

    await server.start();
    console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {

    console.log(err);
    process.exit(1);
});

init();`

![image](https://user-images.githubusercontent.com/29942842/134142872-4f4091d2-7df8-4ea2-a24e-c4e201e38130.png)
Let me know if you still need some more info. The path is admin but still, rate limit is being applied to it even though I mentioned it to be true in the skip attribute.

**Comment by marcuspoehls** [comment]
@varun17398 Hey Sai, thank you for sharing all the details in this issue. It seems like you’re right and the plugin doesn’t skip rate-limiting the admin route.

Some thoughts I have
- did you check if the return value inside of the `async skip(request)` method returns `true`?
- which versions of `hapi` and `hapi-rate-limitor` are you using?

**Comment by varun17398** [comment]
Hi @marcuspoehls , Yeah I have checked the return value and it's returning fine. I mean I defined that similar function inside the handler and it returned true. In another case when we make a request call skip function never actually gets called. I guess that is also one thing that needs to be checked.

hapi version is 20.1.5
hapi-rate-limitor version is 3.1.1

**Comment by marcuspoehls** [comment]
@varun17398 I guess I found your problem: you’re not passing down the `hapi-rate-limitor` plugin options correctly.

You must use the `options` object inside the `server.register` call to pass through the hapi-rate-limitor options:

```
await server.register({
    plugin: require('hapi-rate-limitor'),
    options: {
      // the plugin options need to be here, inside the `options` object

      max: 10,
      …
    }
})
```

**Comment by varun17398** [comment]
Hi @marcuspoehls , thanks for the quick help it worked. Also I have one doubt like what things from the hapi version 13 make this plugin not work. I just got to know that we are using hapi 13.4.1. So can you tell me if there any security issues w.r.t that hapi version. If it works with hapi 13 as well then what might be challenges we can face.

Please any kind of info on the above is really helpful.

**Comment by marcuspoehls** [comment]
I’m not sure if this plugin works with hapi 13. I remember creating the version 1.0 for hapi 16. Not sure if the hapi 16 plugin system is compatible with hapi 13. If yes, you could use hapi-rate-limitor version 1.0.0. But then you must also follow the hapi-rate-limitor docs and options available for 1.0. Some of the options were introduced in later versions.

**Comment by varun17398** [comment]
Oh okay. I will definitely try that. Also any risk or edge cases you might think that this might miss with lower versions of hapi?

I mean is there any specific reason why it won't support for lesser version. Is this built only after hapi 16 or do lower versions of hapi has some issues due to which this plugin isn't supported there?

**Comment by marcuspoehls** [comment]
I just checked the 1.x tree: https://github.com/futurestudio/hapi-rate-limitor/tree/v1.1.1

I started building this plugin for hapi 17 (not even 16). The reason it doesn’t support lower version is because hapi had deprecated lower versions. I didn’t put any effort into making this plugin compatible with outdated and unsupported hapi versions.
