### ISSUE TITLE
Hiding / Removing the "X-Rate-Limit-Limit" and other headers

### ISSUE THREAD

**Issue by eliyahu2** [futurestudio/hapi-rate-limitor#201]
Is there a way to hide those in the response or are those required? what are they used for? 
there is no documentation for why they are set besides a simple note... 
![image](https://user-images.githubusercontent.com/82314619/149125130-ede09e31-4c90-4b34-98c4-3dffee9b810e.png)

Plus, trying to remove them in "onReponse" by setting them to null doesn't work, how can it be done?

Thanks

**Comment by marcuspoehls** [comment]
@eliyahu2 Hey, the `X-Rate-Limit-*` headers can be used to check your rate limit. For example, if you don’t have any `-Remaining` requests, you can calculate the number of seconds using `-Reset` until you can send another request that won’t be rate-limited.

Does that answer your question?

**Comment by eliyahu2** [comment]
Hi! Thank you for your quick response, actually We're looking to know:

1. Can the X-Rate-Limit-* flags be removed? is it crucial for the rate limiter to work?

2. In the case that it can be removed, how can it be done? We've tried settings the response.header('X-Rate-Limit-Limit', null) during the "OnPreResponse" stage of hapi but it can still be shown in the browser.

Thank you very much for your assistance

**Comment by marcuspoehls** [comment]
@eliyahu2 At this point, there’s no option to disable the rate-limiting headers when rate-limiting applies to a route. If I remember correctly, this plugin won’t set these response headers if a route is not rate-limited.

My approach to remove the headers if you don’t want them:
- register an `onPreResponse` extension point **after** the `hapi-rate-limitor` plugin has been registered
- your extension point will then be called after the plugin
- in your extension point, remove the response headers you don’t want
- you can have a look at the [`assignHeaders` method of this plugin](https://github.com/futurestudio/hapi-rate-limitor/blob/0aae2b6452f73b920b880415cd06e7993d7c7ee3/lib/rate-limiter.js#L482) how to set a response header in hapi
- you can reset a response header by setting the value to `null` or `undefined`

**Comment by eliyahu2** [comment]
@marcuspoehls Thanks That's very helpful!

**Comment by marcuspoehls** [comment]
Nice 😊🤜🤛

**Comment by marcuspoehls** [comment]
@eliyahu2 I saw you reopened this issue. Do you need help?
