### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by AdriVanHoudt** [futurestudio/hapi-rate-limitor#203]
Hey,

Would it be possible to release a version with all the updates deps?
Thanks for keeping things updated!

**Comment by AdriVanHoudt** [comment]
No problem! Thanks for keeping things up to date 🙏

**Comment by marcuspoehls** [comment]
@AdriVanHoudt Hey Adri, I’ve published version `3.1.2` to NPM.

**Comment by AdriVanHoudt** [comment]
Awesome thanks!
