### ISSUE TITLE
How do I pass REDIS_URL as option?

### ISSUE THREAD

**Issue by BigWillie** [futurestudio/hapi-rate-limitor#29]
I'm trying to use this in an app that runs on Dokku (using dokku redis) I've added the environment variables, but get  

`[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.`

Dokku redis does not give the password as an environment variable. However, the password is available as part of a URL connection string https://github.com/dokku/dokku-redis

>   REDIS_URL=redis://lolipop:SOME_PASSWORD@dokku-redis-lolipop:6379

How would I pass this URL as an an option? (I'm using glue)

```
{
        plugin: require('hapi-rate-limitor'),
        options: {
          redis: {
            port: process.env["DDOKKU_REDIS_CCREDIS_PORT_6379_TCP_PORT"],
            host: process.env["DOKKU_REDIS_CCREDIS_PORT_6379_TCP_ADDR"],
          },
          max: 3600,
          duration: 60 * 60 * 1000, // 1h
          extensionPoint: 'onPreAuth',
          namespace: 'hapi-rate-limitor'
        }
      },
```

**Comment by marcuspoehls** [comment]
@BigWillie Hey Rob, we talked about ruins issue in Slack. Just wanted to ack the issue here and confirm that the current version 2.7 of hapi-rate-limitor doesn't support a full Redis connection string. You'd have to parse the string to an object to make it work. Thank you for taking the time and putting in the effort to prepare a PR for this feature 😍

**Comment by marcuspoehls** [comment]
Merged #37. This will be fixed with the upcoming release

**Comment by marcuspoehls** [comment]
@BigWillie Hey Rob, I’ve tagged release `2.8.0` including support for the Redis connection string. Thank you very much for your contribution!

**Comment by vinaykumar612** [comment]
Is there any way to implement without `redis`

**Comment by marcuspoehls** [comment]
@vinaykumar612 Hey, Redis is required for this package. We’re storing the rate-limiting history and information in Redis
